### ISSUE TITLE
/etc/conf.d/hostname heredoc lacks quoting

### ISSUE THREAD

**Issue by hartwork** [prometheanfire/gentoo-cloud-prep#12]
Hi!
The current code produces this final `/etc/conf.d/hostname` content:

```
# Set to the hostname of this machine
if [ -f /etc/hostname ];then
  hostname=
else
  hostname="localhost"
fi
```

That's because

```
cat > /etc/conf.d/hostname << EOL
```

lacks quoting, i.e. `EOL` should be `"EOL"` instead at https://github.com/prometheanfire/gentoo-cloud-prep/blob/master/files/prep.sh#L42-L49.

**Comment by prometheanfire** [comment]
yep, just tested this fix, will commit shortly
