### ISSUE TITLE
2015-07-22 image lacks /usr/portage/profiles/ ?

### ISSUE THREAD

**Issue by hartwork** [prometheanfire/gentoo-cloud-prep#13]
As a consequence I can neither emerge anything nor select a profile:

```
$ sudo emerge nano
setlocale: unsupported locale setting
!!! Repository 'x-portage' is missing masters attribute in '/usr/portage/metadata/layout.conf'
!!! Set 'masters = gentoo' in this file for future compatibility


!!! /etc/portage/make.profile is not a symlink and will probably prevent most merges.
!!! It should point into a profile within /usr/portage/profiles/
!!! (You can safely ignore this message when syncing. It's harmless.)


!!! Your current profile is invalid. If you have just changed your profile
!!! configuration, you should revert back to the previous configuration.
!!! Allowed actions are limited to --help, --info, --search, --sync, and
!!! --version.

$ eselect profile list
!!! Error: Failed to get a list of valid profiles
exiting

$ ls -l /usr/portage/profiles/
ls: cannot access /usr/portage/profiles/: No such file or directory
```

**Comment by prometheanfire** [comment]
you need to emerge --sync (better to emerge-webrsync imo).

**Comment by hartwork** [comment]
Come on :) I can install packages out of the box with any other distro's OpenStack image.
If you really want it that way, the user needs to know from inside the image, through MOTD or something at least.

**Comment by prometheanfire** [comment]
fair enough, I'll make a note of it for them, the reason I don't ship /usr/portage is it doubles the image size, same for /usr/src/linux

**Comment by hartwork** [comment]
Personally, I'd still ship it, no matter the size.

**Comment by prometheanfire** [comment]
don't think motd is the right place, think it should be outside docs about it, maybe just a readme placed in the upload dir.  motds are too long lasting

**Comment by hartwork** [comment]
The person booting the image may not be the one who downloaded and installed the image. So he/she won't know. My vote for inside the image. The not itself could say how to remove the note.

**Comment by prometheanfire** [comment]
I am tempted to include /usr/portage, not totally sure about it.  will ask around for more opinions

**Comment by prometheanfire** [comment]
ok, only about a 150M growth in size, not as bad as I thought (150% vs 200%)

**Comment by hartwork** [comment]
:+1: for including `/usr/portage`

**Comment by prometheanfire** [comment]
I'm working on new images, but it looks like portage is sad right now with a conflict between attr and man-pages

**Comment by hartwork** [comment]
If you feel like mailing or posting details, I'd be interested.

**Comment by hartwork** [comment]
(reverted the title rename to match the actual solution)
