### ISSUE TITLE
change default block size to 8k

### ISSUE THREAD

**Issue by prometheanfire** [prometheanfire/gentoo-cloud-prep#16]
better for usage over iscsi I think (and specifically zvols)

**Comment by prometheanfire** [comment]
`mkfs.ext4 -b 8192 /dev/sda3`

**Comment by hartwork** [comment]
May I ask why?

**Comment by prometheanfire** [comment]
more efficient use of networking, more efficient use of solid state drives.

**Comment by prometheanfire** [comment]
might actually be better to switch to xfs...

**Comment by hartwork** [comment]
Why?

**Comment by prometheanfire** [comment]
just a guess, but I think the way that xfs works would be better for iscsi (and better in general, as it's generally better then ext4), I need to research some of the drawbacks (specifically the safety aspects).

**Comment by prometheanfire** [comment]
well, ext4 is faster 1.4 times faster in fact, closing :D
