### ISSUE TITLE
Image of 2015-06-23 does not boot

### ISSUE THREAD

**Issue by hartwork** [prometheanfire/gentoo-cloud-prep#9]
Hi!
I gave [openstack-amd64-_default_-_20150623_.qcow2](http://distfiles.gentoo.org/experimental/amd64/openstack/openstack-amd64-default-20150623.qcow2) a try today.
Using noVNC I can see that after selecting the first GRUB entry, an error

```
error: no suche device: 3d849a77-b17d-4e9f-ab87-a23c23d0ddd8
```

is displayed and the boot process hangs a few steps after that, see screenshots, below.

![gentoo-openstack-1](https://cloud.githubusercontent.com/assets/1577132/8520713/3696bb6c-23dd-11e5-9c0b-e6ed352ce463.png)
![gentoo-openstack-2](https://cloud.githubusercontent.com/assets/1577132/8520714/369cc35e-23dd-11e5-8428-99b361fc44b8.png)

**Comment by prometheanfire** [comment]
ya, the uuid changes if I remember correctly, need to fix that

**Comment by prometheanfire** [comment]
you tried running this in openstack? works with kilo for me

**Comment by hartwork** [comment]
OpenStack, yes. Not sure which version. I am end user of that setup, only.

**Comment by subsecond** [comment]
Tested with OpenStack Kilo Release (Ubuntu 14.04.2 LTS), same behaviour as described by @hartwork.

Rest assured that all the other images I tested are pristine as well and work out of the box (Ubuntu, Debian, CentOS, Fedora, FreeBSD).

Once the experimental Gentoo image gets fixed, it might be interesting to list it in the official OpenStack image guide: http://docs.openstack.org/image-guide/content/ch_obtaining_images.html

**Comment by prometheanfire** [comment]
master generates good images

**Comment by hartwork** [comment]
It would be cool if you could upload new images to http://distfiles.gentoo.org/experimental/amd64/openstack/ . Right now, 2015-06-23 seems to remain the latest.

**Comment by prometheanfire** [comment]
I'm gonna be generating images tonight, but it will be after the deadline for upload there.  Need to wait for some fixes to hit the portage tarball, then generate the images and upload.  so they should be up in about 32 hours.
